services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastor-site
    restart: always
    ports:
      - "49152:49152"
    environment:
      - NODE_ENV=production
